export const carClients = [
  {
    first_name: "Amelia",
    last_name: "Washington",
    email: "amelia.washington@gmail.com",
    make: "Chevrolet",
    model: "Suburban 1500",
    model_year: "2009",
    vin: "ZRE9CCY09UGD06410",
    date: "10/4/2020",
    color: "Persimmon",
  },
  {
    first_name: "Amber",
    last_name: "Nelson",
    email: "amber_nelson88@hotmail.com",
    make: "GMC",
    model: "Suburban 1500",
    model_year: "1997",
    vin: "Y42Y7WMKV4WG01538",
    date: "2/2/2012",
    color: "Deep chestnut",
  },
  {
    first_name: "Steven",
    last_name: "Martinez",
    email: "steven.thomas@outlook.com",
    make: "Chevrolet",
    model: "Cruze",
    model_year: "2019",
    vin: "NJPAJFWKRS4T63245",
    date: "4/8/2019",
    color: "Linen",
  },
  {
    first_name: "Kelsey",
    last_name: "Russell",
    email: "karussell@live.com",
    make: "Volvo",
    model: "C30",
    model_year: "2011",
    vin: "8C8Z3R0SUD2C67655",
    date: "2/6/2011",
    color: "Bittersweet",
  },
  {
    first_name: "Sara",
    last_name: "Torres",
    email: "s_l_torres@outlook.com",
    make: "Ram",
    model: "ProMaster City",
    model_year: "2019",
    vin: "PMNJYN8AAPFE33158",
    date: "21/9/2020",
    color: "Dark pastel green",
  },
  {
    first_name: "Danielle",
    last_name: "Williams",
    email: "d.williams@yahoo.com",
    make: "Chevrolet",
    model: "Astro Cargo",
    model_year: "1999",
    vin: "C03VEDVT6E4574014",
    date: "14/6/2010",
    color: "Café noir",
  },
  {
    first_name: "Jonathan",
    last_name: "Taylor",
    email: "j.r@hotmail.com",
    make: "GMC",
    model: "Suburban 2500",
    model_year: "1999",
    vin: "JHP4ASEDPG1X62046",
    date: "16/1/2018",
    color: "Polished Pine",
  },
  {
    first_name: "Ashley",
    last_name: "Mitchell",
    email: "ashley.mitchell@live.com",
    make: "Cadillac",
    model: "ATS-V",
    model_year: "2016",
    vin: "51S3T53AP7HS99446",
    date: "2/12/2016",
    color: "Dark orange",
  },
  {
    first_name: "Owen",
    last_name: "Bailey",
    email: "owen.w.bailey@aol.com",
    make: "Jaguar",
    model: "S-Type",
    model_year: "2007",
    vin: "U1YBZVB988CZ53846",
    date: "3/8/2015",
    color: "Illuminating emerald",
  },
  {
    first_name: "Jack",
    last_name: "Morris",
    email: "j_c_morris@rocketmail.com",
    make: "GMC",
    model: "Safari Cargo",
    model_year: "1993",
    vin: "XRTGAFJEKMM543904",
    date: "8/8/2019",
    color: "Solid pink",
  },
  {
    first_name: "Olivia",
    last_name: "Stewart",
    email: "olivia@gmail.com",
    make: "Honda",
    model: "Odyssey",
    model_year: "2009",
    vin: "6D8WWCHG0BSR83247",
    date: "24/8/2014",
    color: "China pink",
  },
  {
    first_name: "Nicole",
    last_name: "Brown",
    email: "n.f.brown@hotmail.com",
    make: "Pontiac",
    model: "GTO",
    model_year: "2006",
    vin: "CRT2PX09MVDZ51957",
    date: "11/12/2017",
    color: "Gold Fusion",
  },
  {
    first_name: "Katherine",
    last_name: "Allen",
    email: "k_r_allen@ymail.com",
    make: "GMC",
    model: "1500 Regular Cab",
    model_year: "1997",
    vin: "66K3S7BYG2SG80952",
    date: "26/5/2022",
    color: "Turtle green",
  },
  {
    first_name: "Samantha",
    last_name: "Wilson",
    email: "samantha_m_wilson83@gmail.com",
    make: "Toyota",
    model: "Highlander",
    model_year: "2005",
    vin: "A1HML64WTPBB64121",
    date: "26/4/2012",
    color: "Dark liver",
  },
  {
    first_name: "Maria",
    last_name: "Butler",
    email: "m_m_butler@hotmail.com",
    make: "Volvo",
    model: "S60",
    model_year: "2018",
    vin: "L1T44FG3PVSS40779",
    date: "17/8/2013",
    color: "Resolution blue",
  },
  {
    first_name: "Claire",
    last_name: "Jackson",
    email: "claire_jackson@yahoo.com",
    make: "Audi",
    model: "S3",
    model_year: "2018",
    vin: "PH4MHP2X3AZ095976",
    date: "26/7/2014",
    color: "Purpureus",
  },
  {
    first_name: "Laura",
    last_name: "Rodriguez",
    email: "laura.louise.rodriguez@yahoo.com",
    make: "Chevrolet",
    model: "G-Series 3500",
    model_year: "1997",
    vin: "RH3B176FWRNE27191",
    date: "28/6/2011",
    color: "Baby pink",
  },
  {
    first_name: "Oliver",
    last_name: "Alexander",
    email: "oliver.francis.alexander78@outlook.com",
    make: "Lincoln",
    model: "Aviator",
    model_year: "2003",
    vin: "3XSMLG5CGBHV65199",
    date: "24/1/2012",
    color: "Lemon meringue",
  },
  {
    first_name: "John",
    last_name: "Morris",
    email: "john.a@hotmail.com",
    make: "Chevrolet",
    model: "Silverado 2500 HD Crew Cab",
    model_year: "2004",
    vin: "SX66SMSMMXX082757",
    date: "9/7/2011",
    color: "Paradise pink",
  },
  {
    first_name: "Kevin",
    last_name: "Rogers",
    email: "k_rogers@gmail.com",
    make: "MINI",
    model: "Convertible",
    model_year: "2005",
    vin: "73EZKXWC92MR69183",
    date: "7/11/2015",
    color: "Mango Tango",
  },
  {
    first_name: "Olivia",
    last_name: "Parker",
    email: "olivia.parker92@ymail.com",
    make: "Cadillac",
    model: "CT6",
    model_year: "2017",
    vin: "KRJMDJ2N6XV345047",
    date: "11/11/2019",
    color: "Blue-green",
  },
  {
    first_name: "Layla",
    last_name: "Phillips",
    email: "layla.phillips@aol.com",
    make: "Hyundai",
    model: "Equus",
    model_year: "2014",
    vin: "FN2JKXVU3DRU11406",
    date: "19/5/2016",
    color: "Avocado",
  },
  {
    first_name: "Oliver",
    last_name: "Davis",
    email: "o.r.davis@rocketmail.com",
    make: "Chevrolet",
    model: "Express 3500 Cargo",
    model_year: "2005",
    vin: "3S0FV5360M0W86267",
    date: "4/4/2020",
    color: "Amaranth pink",
  },
  {
    first_name: "Layla",
    last_name: "James",
    email: "l.d.james@rocketmail.com",
    make: "Dodge",
    model: "Ram 3500 Club Cab",
    model_year: "1995",
    vin: "9Y4V7WSGFTZ275718",
    date: "7/7/2016",
    color: "Light gray",
  },
  {
    first_name: "Oliver",
    last_name: "Turner",
    email: "oliver_james@ymail.com",
    make: "GMC",
    model: "Safari Passenger",
    model_year: "1998",
    vin: "EPEBSC269UPU91362",
    date: "18/6/2017",
    color: "Picotee blue",
  },
  {
    first_name: "Jack",
    last_name: "Robinson",
    email: "jack_robinson@aol.com",
    make: "Chevrolet",
    model: "Equinox",
    model_year: "2018",
    vin: "JTXWWW1X4NMG54788",
    date: "29/5/2012",
    color: "St. Patrick's blue",
  },
  {
    first_name: "Matthew",
    last_name: "Barnes",
    email: "mjbarnes@ymail.com",
    make: "Volvo",
    model: "S80",
    model_year: "2001",
    vin: "ZVD2L1UFMM3V74755",
    date: "12/1/2021",
    color: "Rose vale",
  },
  {
    first_name: "Joseph",
    last_name: "Jones",
    email: "j.jones@outlook.com",
    make: "Chevrolet",
    model: "Cobalt",
    model_year: "2008",
    vin: "CPLP5VPX6G2J11444",
    date: "5/5/2017",
    color: "Hot magenta",
  },
  {
    first_name: "Layla",
    last_name: "Hughes",
    email: "laylakhughes58@live.com",
    make: "GMC",
    model: "Vandura 3500",
    model_year: "1993",
    vin: "WCM5Z8LUAGYS71856",
    date: "3/2/2018",
    color: "Wintergreen Dream",
  },
  {
    first_name: "Richard",
    last_name: "Alexander",
    email: "richard@ymail.com",
    make: "Dodge",
    model: "Viper",
    model_year: "1994",
    vin: "7T4XJB9XWHH973016",
    date: "16/9/2021",
    color: "Purple",
  },
  {
    first_name: "James",
    last_name: "Alexander",
    email: "jaalexander@outlook.com",
    make: "Ford",
    model: "F350 Crew Cab",
    model_year: "1995",
    vin: "63V7VRD4HCX625580",
    date: "25/3/2018",
    color: "Sugar Plum",
  },
  {
    first_name: "Sophia",
    last_name: "Green",
    email: "sophia_m_green@yahoo.com",
    make: "Ford",
    model: "E150 Passenger",
    model_year: "2012",
    vin: "RCX4N486KD8L78186",
    date: "24/4/2021",
    color: "Byzantine",
  },
  {
    first_name: "Charles",
    last_name: "Foster",
    email: "charles_foster@live.com",
    make: "Chevrolet",
    model: "Blazer",
    model_year: "2001",
    vin: "9V0B66ZNYBBU95908",
    date: "4/4/2012",
    color: "Blue-green",
  },
  {
    first_name: "Oliver",
    last_name: "Sanders",
    email: "osanders@aol.com",
    make: "Land Rover",
    model: "Discovery Sport",
    model_year: "2015",
    vin: "V1TJL253F83J04878",
    date: "23/6/2015",
    color: "Sand dune",
  },
  {
    first_name: "Joshua",
    last_name: "Ward",
    email: "joshuaward@hotmail.com",
    make: "Ram",
    model: "3500 Regular Cab",
    model_year: "2019",
    vin: "HNZDYK1M34D901162",
    date: "22/8/2015",
    color: "Razzmic Berry",
  },
  {
    first_name: "Gabriel",
    last_name: "Stewart",
    email: "gabriel.stewart@live.com",
    make: "Kia",
    model: "Spectra",
    model_year: "2007",
    vin: "0VYXGCJTR6YN84503",
    date: "12/1/2017",
    color: "Middle blue",
  },
  {
    first_name: "Dylan",
    last_name: "Adams",
    email: "d_j_adams@gmail.com",
    make: "Ferrari",
    model: "488 GTB",
    model_year: "2016",
    vin: "VH6K2M46CTJ572240",
    date: "17/11/2021",
    color: "Eggplant",
  },
  {
    first_name: "Anthony",
    last_name: "Hill",
    email: "ahill@outlook.com",
    make: "Oldsmobile",
    model: "Silhouette",
    model_year: "1998",
    vin: "XJF3CSKCKFUR46023",
    date: "13/7/2011",
    color: "Candy pink",
  },
  {
    first_name: "James",
    last_name: "Adams",
    email: "james@yahoo.com",
    make: "Buick",
    model: "Century",
    model_year: "1999",
    vin: "C4V6PLCKPRV070253",
    date: "16/2/2021",
    color: "Midnight green",
  },
  {
    first_name: "Mateo",
    last_name: "Powell",
    email: "mpowell@yahoo.com",
    make: "BMW",
    model: "X3",
    model_year: "2014",
    vin: "YS256WMLTU5M63485",
    date: "24/9/2015",
    color: "Champagne",
  },
  {
    first_name: "David",
    last_name: "Bennett",
    email: "david@hotmail.com",
    make: "GMC",
    model: "Savana 1500 Passenger",
    model_year: "1998",
    vin: "S1S7EEAGNLB400906",
    date: "2/10/2012",
    color: "Gray",
  },
  {
    first_name: "Natalie",
    last_name: "Sanders",
    email: "nmsanders@live.com",
    make: "Hyundai",
    model: "Tiburon",
    model_year: "2000",
    vin: "6LMJY1YDVHH822779",
    date: "24/8/2022",
    color: "Nyanza",
  },
  {
    first_name: "Claire",
    last_name: "Anderson",
    email: "c_a_anderson@gmail.com",
    make: "Rolls-Royce",
    model: "Phantom",
    model_year: "2007",
    vin: "A6PZVMV8NGZE61904",
    date: "9/10/2010",
    color: "Raisin black",
  },
  {
    first_name: "Henry",
    last_name: "Davis",
    email: "hddavis@gmail.com",
    make: "Volkswagen",
    model: "Tiguan Limited",
    model_year: "2017",
    vin: "V7EYYCK6W1V644711",
    date: "7/9/2012",
    color: "Medium aquamarine",
  },
  {
    first_name: "Benjamin",
    last_name: "Coleman",
    email: "benjamincoleman@gmail.com",
    make: "Cadillac",
    model: "Escalade",
    model_year: "2008",
    vin: "DP5NW9S7YGKZ43049",
    date: "22/7/2011",
    color: "Solid pink",
  },
  {
    first_name: "Timothy",
    last_name: "Carter",
    email: "tcarter@outlook.com",
    make: "Chevrolet",
    model: "Corvette",
    model_year: "1992",
    vin: "XGA6AHWPS9P795703",
    date: "21/8/2018",
    color: "Silver chalice",
  },
  {
    first_name: "Eleanor",
    last_name: "Lee",
    email: "eleanor_a_lee@ymail.com",
    make: "Chevrolet",
    model: "Silverado 2500 HD Regular Cab",
    model_year: "2007",
    vin: "LPBSH6CSH7NZ64280",
    date: "9/1/2019",
    color: "Green",
  },
  {
    first_name: "Samuel",
    last_name: "Griffin",
    email: "s.griffin@live.com",
    make: "Nissan",
    model: "370Z",
    model_year: "2012",
    vin: "Y3KCH6F0VJNA08362",
    date: "23/11/2021",
    color: "Periwinkle",
  },
  {
    first_name: "Owen",
    last_name: "Johnson",
    email: "owen.johnson@aol.com",
    make: "Ford",
    model: "Aerostar Passenger",
    model_year: "1995",
    vin: "TU1VVYD4J19842682",
    date: "21/6/2010",
    color: "Citron",
  },
  {
    first_name: "Joshua",
    last_name: "Thompson",
    email: "joshua.thompson@yahoo.com",
    make: "Toyota",
    model: "FJ Cruiser",
    model_year: "2009",
    vin: "SSK5LEZKJGS894557",
    date: "16/4/2016",
    color: "Tomato",
  },
  {
    first_name: "Mateo",
    last_name: "Hughes",
    email: "m_hughes@gmail.com",
    make: "Ford",
    model: "Taurus X",
    model_year: "2009",
    vin: "0JW7BA5ZUMKZ47755",
    date: "27/9/2017",
    color: "Green",
  },
  {
    first_name: "Isaac",
    last_name: "Robinson",
    email: "i_c_robinson@rocketmail.com",
    make: "Subaru",
    model: "BRZ",
    model_year: "2018",
    vin: "G0GW24J94J9G83351",
    date: "17/8/2010",
    color: "Rufous",
  },
  {
    first_name: "Jeremy",
    last_name: "Alexander",
    email: "j.alexander@outlook.com",
    make: "Land Rover",
    model: "Range Rover",
    model_year: "2002",
    vin: "UPRNXYEG7Y3X14272",
    date: "28/7/2016",
    color: "Arylide yellow",
  },
  {
    first_name: "John",
    last_name: "Evans",
    email: "john_evans@gmail.com",
    make: "BMW",
    model: "X6",
    model_year: "2017",
    vin: "NDHDJA1G7STW64458",
    date: "24/11/2013",
    color: "Citrine",
  },
  {
    first_name: "Emily",
    last_name: "Lopez",
    email: "e_lopez@outlook.com",
    make: "Land Rover",
    model: "Discovery Series II",
    model_year: "2000",
    vin: "DZZMFBXEXC5011629",
    date: "12/8/2011",
    color: "Lava",
  },
  {
    first_name: "Henry",
    last_name: "Lewis",
    email: "hjlewis@aol.com",
    make: "GMC",
    model: "Canyon Crew Cab",
    model_year: "2010",
    vin: "S26CS41T0SF198268",
    date: "24/5/2022",
    color: "Patriarch",
  },
  {
    first_name: "Timothy",
    last_name: "Mitchell",
    email: "t.j.mitchell@hotmail.com",
    make: "Chevrolet",
    model: "Caprice Classic",
    model_year: "1996",
    vin: "LPXG2M5TRX4M44950",
    date: "29/8/2018",
    color: "Maximum blue",
  },
  {
    first_name: "Dylan",
    last_name: "Torres",
    email: "dhtorres@aol.com",
    make: "Lexus",
    model: "ES",
    model_year: "2014",
    vin: "R01UW3MM1K4738524",
    date: "15/3/2010",
    color: "Tyrian purple",
  },
  {
    first_name: "Zachary",
    last_name: "Evans",
    email: "zacharyhenry@aol.com",
    make: "GMC",
    model: "1500 Regular Cab",
    model_year: "1998",
    vin: "8C9YVHBVE8JH63105",
    date: "24/6/2017",
    color: "Silver",
  },
  {
    first_name: "Jonathan",
    last_name: "Smith",
    email: "jonathan_smith@outlook.com",
    make: "INFINITI",
    model: "QX80",
    model_year: "2014",
    vin: "B8EJV4AJRUZB77287",
    date: "28/6/2021",
    color: "Cadmium orange",
  },
  {
    first_name: "Maria",
    last_name: "Green",
    email: "maria_green15@ymail.com",
    make: "Mitsubishi",
    model: "Montero",
    model_year: "1999",
    vin: "4FHETV8Z07RT87904",
    date: "3/2/2014",
    color: "Queen pink",
  },
  {
    first_name: "Andrew",
    last_name: "White",
    email: "am@hotmail.com",
    make: "Nissan",
    model: "Frontier Crew Cab",
    model_year: "2015",
    vin: "YTEUAW5F63W481118",
    date: "28/2/2018",
    color: "Pink flamingo",
  },
  {
    first_name: "Steven",
    last_name: "Thompson",
    email: "s_j@rocketmail.com",
    make: "Jeep",
    model: "Cherokee",
    model_year: "2014",
    vin: "HYBHFHP7KAKC19605",
    date: "2/5/2016",
    color: "Battleship grey",
  },
  {
    first_name: "Elizabeth",
    last_name: "Bennett",
    email: "embennett@aol.com",
    make: "Land Rover",
    model: "Range Rover Sport",
    model_year: "2008",
    vin: "GVAU9CN21RWC27876",
    date: "17/1/2019",
    color: "Phthalo green",
  },
  {
    first_name: "Robert",
    last_name: "Washington",
    email: "r.washington13@ymail.com",
    make: "INFINITI",
    model: "M",
    model_year: "1992",
    vin: "A96P0KVZKLEP88785",
    date: "14/3/2011",
    color: "Dark red",
  },
  {
    first_name: "Richard",
    last_name: "Moore",
    email: "richard_william_moore95@outlook.com",
    make: "Daihatsu",
    model: "Rocky",
    model_year: "1992",
    vin: "CRFKGAU95EZX03003",
    date: "26/1/2016",
    color: "Onyx",
  },
  {
    first_name: "Stephen",
    last_name: "Anderson",
    email: "stephen.w@yahoo.com",
    make: "Chevrolet",
    model: "Tahoe",
    model_year: "1997",
    vin: "P5JGMZ74MMAV09532",
    date: "19/10/2020",
    color: "Pale purple",
  },
  {
    first_name: "Ryan",
    last_name: "Simmons",
    email: "r_simmons52@live.com",
    make: "GMC",
    model: "Savana 3500 Cargo",
    model_year: "2002",
    vin: "H7GR588UP1NW61981",
    date: "29/4/2022",
    color: "Dark slate blue",
  },
  {
    first_name: "Matthew",
    last_name: "Russell",
    email: "matthewlrussell84@yahoo.com",
    make: "Subaru",
    model: "Impreza",
    model_year: "2007",
    vin: "BMGEE6WV13Y079744",
    date: "27/2/2014",
    color: "Violet-red",
  },
  {
    first_name: "John",
    last_name: "Roberts",
    email: "john.roberts@aol.com",
    make: "Lincoln",
    model: "MKC",
    model_year: "2017",
    vin: "S0G4JLUKR11X86819",
    date: "13/2/2012",
    color: "Peach",
  },
  {
    first_name: "Emma",
    last_name: "Henderson",
    email: "eghenderson@gmail.com",
    make: "Dodge",
    model: "Dakota Club Cab",
    model_year: "2006",
    vin: "8RXTW6ZBVEK491395",
    date: "1/12/2014",
    color: "Maximum blue green",
  },
  {
    first_name: "Stephen",
    last_name: "Cox",
    email: "stephen_a_cox@rocketmail.com",
    make: "Dodge",
    model: "Durango",
    model_year: "2000",
    vin: "NBFKKUM3FNVV92810",
    date: "6/12/2014",
    color: "Paradise pink",
  },
  {
    first_name: "John",
    last_name: "Diaz",
    email: "j_diaz@aol.com",
    make: "Toyota",
    model: "RAV4",
    model_year: "2010",
    vin: "W1B27B02LV9477087",
    date: "8/1/2022",
    color: "Yellow-green",
  },
  {
    first_name: "Erin",
    last_name: "Thomas",
    email: "erin.thomas@outlook.com",
    make: "Ram",
    model: "1500 Crew Cab",
    model_year: "2019",
    vin: "H51Z6XEU60B934660",
    date: "11/2/2018",
    color: "Orange-red",
  },
  {
    first_name: "Richard",
    last_name: "Collins",
    email: "richardjcollins@aol.com",
    make: "Ford",
    model: "Freestar Cargo",
    model_year: "2007",
    vin: "CD4NHPZY1HJF76611",
    date: "29/8/2010",
    color: "French violet",
  },
  {
    first_name: "Sara",
    last_name: "Turner",
    email: "s.d.turner@hotmail.com",
    make: "Scion",
    model: "FR-S",
    model_year: "2014",
    vin: "PCPU8K59YM5B09994",
    date: "11/5/2015",
    color: "Red-purple",
  },
  {
    first_name: "Emma",
    last_name: "Martin",
    email: "emma_martin@aol.com",
    make: "Dodge",
    model: "Ram Van B250",
    model_year: "1993",
    vin: "BLW2VY0T0WH385203",
    date: "14/11/2017",
    color: "Air superiority blue",
  },
  {
    first_name: "Michael",
    last_name: "Johnson",
    email: "mrjohnson@aol.com",
    make: "Mercury",
    model: "Sable",
    model_year: "2008",
    vin: "TSZCTNUV36NV92289",
    date: "8/5/2010",
    color: "Fallow",
  },
  {
    first_name: "Jessica",
    last_name: "Campbell",
    email: "jessica.campbell@yahoo.com",
    make: "Volkswagen",
    model: "Jetta III",
    model_year: "1994",
    vin: "4L3WSYPBWE7R19463",
    date: "20/3/2012",
    color: "Fuchsia",
  },
  {
    first_name: "Isabella",
    last_name: "Barnes",
    email: "ibarnes@live.com",
    make: "Oldsmobile",
    model: "Bravada",
    model_year: "1994",
    vin: "65N94M0EYXFE26916",
    date: "19/11/2020",
    color: "Black chocolate",
  },
  {
    first_name: "Rebecca",
    last_name: "Diaz",
    email: "r.diaz14@hotmail.com",
    make: "Suzuki",
    model: "Swift",
    model_year: "1998",
    vin: "FJB1YFE6XTEZ70621",
    date: "16/11/2019",
    color: "Cyan",
  },
  {
    first_name: "Rachel",
    last_name: "Washington",
    email: "racheli@rocketmail.com",
    make: "Isuzu",
    model: "Amigo",
    model_year: "1992",
    vin: "5H1BT098ZTJT72058",
    date: "8/11/2018",
    color: "Coyote brown",
  },
  {
    first_name: "Melissa",
    last_name: "Martin",
    email: "melissanicole@yahoo.com",
    make: "Nissan",
    model: "200SX",
    model_year: "1998",
    vin: "NY69SY8CLB6G24552",
    date: "12/2/2022",
    color: "Spring green",
  },
  {
    first_name: "Rebecca",
    last_name: "Turner",
    email: "r_m_turner@aol.com",
    make: "MINI",
    model: "Cooper",
    model_year: "2004",
    vin: "NFZ1EYBY42EZ54481",
    date: "6/12/2014",
    color: "Green",
  },
  {
    first_name: "Anthony",
    last_name: "Moore",
    email: "anthony_moore@gmail.com",
    make: "Land Rover",
    model: "LR2",
    model_year: "2009",
    vin: "NKH1J17V4CYL01610",
    date: "20/6/2017",
    color: "Violet",
  },
  {
    first_name: "Brandon",
    last_name: "Bennett",
    email: "brandon_bennett@aol.com",
    make: "Dodge",
    model: "Durango",
    model_year: "2006",
    vin: "W8DA2T2MWVUS51352",
    date: "11/10/2019",
    color: "Mandarin",
  },
  {
    first_name: "Amber",
    last_name: "Diaz",
    email: "amberm@yahoo.com",
    make: "Lincoln",
    model: "MKS",
    model_year: "2014",
    vin: "BLP38T2ADU3086638",
    date: "19/10/2017",
    color: "Raspberry rose",
  },
  {
    first_name: "Owen",
    last_name: "Alexander",
    email: "o_alexander@live.com",
    make: "Ford",
    model: "Taurus",
    model_year: "2006",
    vin: "NF18WZGEFJS822736",
    date: "10/10/2017",
    color: "Bright navy blue",
  },
  {
    first_name: "Austin",
    last_name: "Murphy",
    email: "ad@yahoo.com",
    make: "MINI",
    model: "Hardtop 4 Door",
    model_year: "2019",
    vin: "VUHCN02YGGFH17769",
    date: "14/7/2010",
    color: "Pale silver",
  },
  {
    first_name: "Michael",
    last_name: "Reed",
    email: "m_reed@aol.com",
    make: "Honda",
    model: "Odyssey",
    model_year: "1997",
    vin: "GPW43J7LUBTK79309",
    date: "7/11/2020",
    color: "Rose pink",
  },
  {
    first_name: "Taylor",
    last_name: "Davis",
    email: "taylorjdavis@gmail.com",
    make: "BMW",
    model: "X5",
    model_year: "2015",
    vin: "VUHRTE225V0W99869",
    date: "6/10/2018",
    color: "French rose",
  },
  {
    first_name: "Melissa",
    last_name: "Clark",
    email: "m.clark90@aol.com",
    make: "Toyota",
    model: "Prius",
    model_year: "2003",
    vin: "1FRXWTHFHC4F84720",
    date: "1/10/2019",
    color: "Blond",
  },
  {
    first_name: "Brian",
    last_name: "Watson",
    email: "brian_wayne@yahoo.com",
    make: "INFINITI",
    model: "Q",
    model_year: "1996",
    vin: "Y14V1WY2HMEC73283",
    date: "8/5/2020",
    color: "Cadmium yellow",
  },
  {
    first_name: "William",
    last_name: "Cooper",
    email: "williamleecooper@hotmail.com",
    make: "BMW",
    model: "7 Series",
    model_year: "2009",
    vin: "J4HTJMW9PPME59771",
    date: "14/4/2021",
    color: "Tangerine",
  },
  {
    first_name: "Justin",
    last_name: "Perez",
    email: "justin_anthony_perez@hotmail.com",
    make: "Honda",
    model: "Odyssey",
    model_year: "2019",
    vin: "2T63879U67SX56049",
    date: "16/10/2010",
    color: "Medium slate blue",
  },
  {
    first_name: "Joshua",
    last_name: "Patterson",
    email: "joshuajosephpatterson@outlook.com",
    make: "Cadillac",
    model: "CTS-V",
    model_year: "2016",
    vin: "PM8GLJ1JMZTU42801",
    date: "30/3/2014",
    color: "Green-yellow",
  },
  {
    first_name: "Grace",
    last_name: "Clark",
    email: "grace_anne_clark@yahoo.com",
    make: "Chevrolet",
    model: "Silverado 1500 Crew Cab",
    model_year: "2007",
    vin: "KUUJYNX2349C73681",
    date: "29/3/2011",
    color: "Jade",
  },
  {
    first_name: "Brianna",
    last_name: "Clark",
    email: "bkclark@ymail.com",
    make: "BMW",
    model: "7 Series",
    model_year: "2005",
    vin: "E6HEBB8V4Y3M60005",
    date: "2/1/2016",
    color: "Sunset",
  },
  {
    first_name: "Lillian",
    last_name: "Gray",
    email: "lilliangray28@gmail.com",
    make: "Toyota",
    model: "RAV4",
    model_year: "2003",
    vin: "4P0D3P4N20YG31734",
    date: "8/4/2018",
    color: "Blue bell",
  },
  {
    first_name: "Samantha",
    last_name: "Henderson",
    email: "s.henderson16@aol.com",
    make: "Acura",
    model: "NSX",
    model_year: "2019",
    vin: "PL32DHNR84L943795",
    date: "24/10/2013",
    color: "Taupe",
  },
];
