const food = [
  {
    id: 5994,
    uid: 'efcc5c3f-c555-4b17-a30d-576dca27af84',
    dish: 'Caesar Salad',
    description: 'Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.',
    ingredient: 'Pear Juice',
    measurement: '2 teaspoon',
  },
  {
    id: 2129,
    uid: 'dea9c508-9ca8-425e-94b3-4d9c860bc1e1',
    dish: 'Poutine',
    description: 'Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.',
    ingredient: 'Butter Beans',
    measurement: '3 quart',
  },
  {
    id: 1869,
    uid: '0c6c0f78-4c16-4bad-8798-13926d06a177',
    dish: 'Pierogi',
    description: 'Breaded fried chicken with waffles. Served with maple syrup.',
    ingredient: 'Cannellini Beans',
    measurement: '1/4 pint',
  },
  {
    id: 9060,
    uid: '8ab9e6d0-1b73-4d4d-b227-d771dd1622b9',
    dish: 'Peking Duck',
    description: 'Breaded fried chicken with waffles, and a side of maple syrup.',
    ingredient: 'Rosemary',
    measurement: '1/2 tablespoon',
  },
  {
    id: 5599,
    uid: '07a87ef0-01aa-494e-a3aa-16e78d9dbbff',
    dish: 'Mushroom Risotto',
    description: 'Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides.',
    ingredient: 'Kiwi Berries',
    measurement: '1/4 tablespoon',
  },
  {
    id: 4299,
    uid: 'f439c6f1-fa76-4a12-83f2-08c35bc1db3c',
    dish: 'French Fries with Sausages',
    description: 'Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread.',
    ingredient: 'Garam Masala',
    measurement: '1 tablespoon',
  },
  {
    id: 3262,
    uid: 'ab395511-a8ab-44c5-aa03-a2cd0a54938a',
    dish: 'Tuna Sashimi',
    description: 'Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits.',
    ingredient: 'Flat Mushrooms',
    measurement: '1/3 quart',
  },
  {
    id: 7184,
    uid: '9a16722d-58d4-4cb8-9de2-b8beddbd006c',
    dish: 'Stinky Tofu',
    description: 'Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes.',
    ingredient: 'Omega Spread',
    measurement: '1/4 cup',
  },
  {
    id: 8940,
    uid: 'a9315da3-2731-4afe-9d5a-df95afb37568',
    dish: 'Philadelphia Maki',
    description: 'Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant.',
    ingredient: 'Dried Apricots',
    measurement: '3 quart',
  },
  {
    id: 2541,
    uid: '70a705f7-0d35-4a20-8665-09e45e554bbd',
    dish: 'French Toast',
    description: 'Breaded fried chicken with waffles, and a side of maple syrup.',
    ingredient: 'White rice',
    measurement: '2 tablespoon',
  },
];

export default food;
