import { SpreadsheetApiResponse } from '../interfaces/spreadsheet'

export const exampleData: <SpreadsheetApiResponse>  = [
  {
    id: 6443,
    uid: '2a6b765d-bb8f-4ba8-8bd7-1206f7cd36c5',
    vin: 'UJ7L62WC050137789',
    make_and_model: 'Buick Enclave',
    color: 'Orange',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Minivan',
    car_options: [
      'Third Row Seats',
      'Cassette Player',
      'Navigation',
      'Alloy Wheels',
      'Power Seats',
      'A/C: Rear',
      'MP3 (Multi Disc)',
    ],
    specs: [
      'Highline door trim panel',
      'Universal garage door opener',
      'Body color grille',
      'Torsion beam rear suspension w/stabilizer bar',
      'Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages',
    ],
    doors: 4,
    mileage: 44156,
    kilometrage: 89396,
    license_plate: 'VDN-9560',
  },
  {
    id: 1529,
    uid: '87d6c2af-3301-4227-a233-a1fb8df9e0b0',
    vin: 'IJFEJXY57XU759702',
    make_and_model: 'BMW X1',
    color: 'Grey',
    transmission: 'Automatic',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Electric',
    car_type: 'Minivan',
    car_options: [
      'Third Row Seats',
      'Alarm',
      'Power Seats',
      'Power Seats',
      'Airbag: Driver',
    ],
    specs: [
      'Daytime running lights (DRL)',
      '6.5" touch screen display',
      'Anti-lock brake system (ABS) -inc: electronic brake force distribution (EBD), brake assist',
      'Pwr tilt/slide moonroof -inc: 1-touch open/close',
      '4-wheel/4-channel anti-lock brake system (ABS)',
    ],
    doors: 3,
    mileage: 80958,
    kilometrage: 29632,
    license_plate: 'KMG-6450',
  },
  {
    id: 2456,
    uid: '19690126-eb04-4d8a-971c-a1d9a4257cad',
    vin: '9ZS3R1ZYRJP293578',
    make_and_model: 'Dodge Durango',
    color: 'Orange',
    transmission: 'Automatic',
    drive_type: 'AWD',
    fuel_type: 'Gasoline',
    car_type: 'Minivan',
    car_options: [
      'Navigation',
      'A/C: Rear',
      'Cruise Control',
      'A/C: Front',
      'CD (Multi Disc)',
    ],
    specs: [
      'Intermittent rear wiper w/washer',
      'Body color fascias w/bright insert',
      'Run flat tires',
      'Glove box lamp',
      'Quadra-Trac active on demand 4WD system',
      'Cargo area lamp',
      'Rear window defroster',
    ],
    doors: 2,
    mileage: 89393,
    kilometrage: 80692,
    license_plate: 'KGU-7844',
  },
  {
    id: 1907,
    uid: '137f5538-22ff-458e-ab50-a3769a94d598',
    vin: '4LJE26GCZY0V34346',
    make_and_model: 'Lincoln MKS',
    color: 'Orange',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'Electric',
    car_type: 'Hatchback',
    car_options: [
      'Integrated Phone',
      'CD (Single Disc)',
      'CD (Multi Disc)',
      'Airbag: Passenger',
      'AM/FM Stereo',
      'Alloy Wheels',
      'CD (Multi Disc)',
      'Tinted Glass',
    ],
    specs: [
      'Dual illuminated visor vanity mirrors',
      'Dual front 2-stage airbags -inc: passenger occupant classification system w/twin-chamber airbag',
      'Body color door handles',
      'Cargo area lamp',
      'Leather-wrapped shift knob',
    ],
    doors: 4,
    mileage: 19180,
    kilometrage: 19336,
    license_plate: 'JWP-9171',
  },
  {
    id: 9375,
    uid: '87a1128f-b929-4476-9aa4-97b4819588d4',
    vin: '79SJ6CLJIY0225518',
    make_and_model: 'Dodge Charger',
    color: 'Red',
    transmission: 'Automanual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Gasoline',
    car_type: 'Minivan',
    car_options: [
      'Navigation',
      'Power Steering',
      'Tinted Glass',
      'Tinted Glass',
      'A/C: Front',
      'DVD System',
      'Power Locks',
      'Memory Seats',
      'CD (Multi Disc)',
    ],
    specs: [
      'Water-repellent windshield & front door glass',
      'Glove box lamp',
      '20" x 9.0" front & 20" x 10.0" rear aluminum wheels',
      'Pwr accessory delay',
      'Front/rear spot-lamp illumination',
      '1.8L DOHC 16-valve I4 engine -inc: engine cover',
      'Pwr 8-way driver seat w/4-way front passenger seat',
      'Pwr windows -inc: 1-touch open/close',
    ],
    doors: 2,
    mileage: 46045,
    kilometrage: 50480,
    license_plate: 'UFO-5071',
  },
  {
    id: 4647,
    uid: 'e5a459f8-a5dc-4170-8787-1c2e4986fec1',
    vin: 'A4AX6RUSD7FS40380',
    make_and_model: 'Toyota Prius',
    color: 'Black',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'E-85/Gasoline',
    car_type: 'SUV',
    car_options: [
      'Navigation',
      'Alloy Wheels',
      'Tinted Glass',
      'Rear Window Wiper',
      'Fog Lights',
      'Bucket Seats',
      'A/C: Rear',
      'Power Seats',
      'CD (Multi Disc)',
    ],
    specs: [
      'Rain-sensing wipers',
      'Monotone paint',
      'Eco drive indicator',
      'Energy absorbing front/rear bumpers',
      '3.73 axle ratio',
      'Anti-lock brake system (ABS) -inc: electronic brake force distribution (EBD), brake assist',
    ],
    doors: 4,
    mileage: 63936,
    kilometrage: 57515,
    license_plate: 'AGC-3891',
  },
  {
    id: 5913,
    uid: 'df51ebef-5247-4608-b3c7-d6c6acfcbde7',
    vin: '31ND86B3WC0209095',
    make_and_model: 'Lincoln MKS',
    color: 'Orange',
    transmission: 'Automatic',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Convertible',
    car_options: [
      'Leather Interior',
      'Bucket Seats',
      'Integrated Phone',
      'Power Seats',
      'Power Steering',
      'Antilock Brakes',
      'Power Windows',
      'Fog Lights',
    ],
    specs: [
      'Pwr windows -inc: 1-touch open/close',
      'Front/rear spot-lamp illumination',
      '6.1L SRT V8 "Hemi" engine',
      'Electric speed-sensitive variable-assist pwr steering',
      'Highline door trim panel',
    ],
    doors: 3,
    mileage: 48414,
    kilometrage: 48587,
    license_plate: 'XYS-4458',
  },
  {
    id: 2191,
    uid: '0cc6d7ff-889a-41ac-9bea-eae3a872ab85',
    vin: '3SBMU3565G0455048',
    make_and_model: 'Audi A8',
    color: 'Beige',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Minivan',
    car_options: [
      'Airbag: Driver',
      'Power Locks',
      'Cassette Player',
      'Navigation',
      'Antilock Brakes',
      'Premium Sound',
      'Rear Window Defroster',
      'CD (Multi Disc)',
    ],
    specs: [
      'Front/rear crumple zones',
      '"Flipper" liftgate glass',
      '12V pwr outlet',
      'P235/50R18 all-season tires',
      'Child safety rear door locks',
      'Passenger assist handles',
      'Rear door child safety locks',
    ],
    doors: 1,
    mileage: 84830,
    kilometrage: 56432,
    license_plate: 'QNK-2659',
  },
  {
    id: 8524,
    uid: '16cf8464-4fd6-4181-8068-fdd71da38c39',
    vin: 'MY991329BRRL17898',
    make_and_model: 'Chevy Silverado',
    color: 'Red',
    transmission: 'Automanual',
    drive_type: 'RWD',
    fuel_type: 'Ethanol',
    car_type: 'Hatchback',
    car_options: [
      'Alloy Wheels',
      'Power Steering',
      'Leather Interior',
      'Tinted Glass',
      'CD (Single Disc)',
    ],
    specs: [
      'Dual note horn',
      'Electrochromic pwr folding heated mirrors w/memory -inc: puddle lamps, integrated turn signals, auto reverse tilt-down',
      'Energy absorbing front/rear bumpers',
      'Dual-zone automatic climate control system -inc: smog sensor, auto recirculation, clear air filter, pollen filter',
      'Tip start system',
      '625-amp maintenance-free battery',
      'Rear reading & courtesy lamps',
      'Overhead console',
      'Quadra-Trac active on demand 4WD system',
    ],
    doors: 2,
    mileage: 73845,
    kilometrage: 79463,
    license_plate: 'IVX-1780',
  },
  {
    id: 7188,
    uid: '8bd7c76d-f4e4-4969-b6f5-5c4d5fe589a0',
    vin: 'H19C34R9R40Y60184',
    make_and_model: 'Chevy Camero',
    color: 'White',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'Electric',
    car_type: 'Sedan',
    car_options: [
      'A/C: Front',
      'MP3 (Multi Disc)',
      'Rear Window Defroster',
      'Bucket Seats',
      'Navigation',
      'Airbag: Driver',
    ],
    specs: [
      '20" x 9.0" front & 20" x 10.0" rear aluminum wheels',
      'All-position 3-point seat belts -inc: outboard pretensioners & force limiters, dual front pwr shoulder height adjusters, rear outboard emergency auto locking retractors, driver emergency locking retractor',
      'Xenon high-intensity discharge (HID) headlamps -inc: adaptive front lighting system, delayed auto-off',
      '1.8L DOHC 16-valve I4 engine -inc: engine cover',
      'Tire pressure monitoring display',
      '60/40 folding rear seat',
    ],
    doors: 3,
    mileage: 24865,
    kilometrage: 86037,
    license_plate: 'FXI-4670',
  },
  {
    id: 9671,
    uid: 'f5276d87-42c2-4f5e-99bb-19d7c8c5f412',
    vin: '3W0BL034V1BW24631',
    make_and_model: 'Toyota Corolla',
    color: 'Yellow',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'Ethanol',
    car_type: 'SUV',
    car_options: [
      'MP3 (Single Disc)',
      'MP3 (Single Disc)',
      'Alarm',
      'Integrated Phone',
      'Alloy Wheels',
      'Navigation',
      'Rear Window Wiper',
      'Premium Sound',
      'Cruise Control',
    ],
    specs: [
      'Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats',
      'Bright pedals',
      'Highline door trim panel',
      '1-piece chrome window surround',
      'Energy absorbing front/rear bumpers',
      '(2) aux 12V pwr outlets -inc: (1) in center console, (1) w/cigarette lighter',
      'Rear door child safety locks',
      'Rear-window defogger w/auto-off timer',
    ],
    doors: 2,
    mileage: 52400,
    kilometrage: 23046,
    license_plate: 'TLV-8634',
  },
  {
    id: 8915,
    uid: 'b93b205c-a37a-445f-ae61-8a9cfecbd3d2',
    vin: 'SA0XQ7M2HJ0881010',
    make_and_model: 'BMW M5',
    color: 'Grey',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'AM/FM Stereo',
      'Fog Lights',
      'CD (Single Disc)',
      'Power Locks',
      'Airbag: Driver',
    ],
    specs: [
      'Brake assist',
      'Independent strut front suspension w/stabilizer bar',
      'Rear window wiper/washer',
      'Intermittent rear wiper w/washer',
      'Air conditioning w/in-cabin microfilter',
      'Cargo area lamp',
      'Child restraint seat anchors for outboard positions',
      'XM satellite radio receiver -inc: 90 day trial subscription',
    ],
    doors: 3,
    mileage: 30655,
    kilometrage: 69675,
    license_plate: 'RHE-1728',
  },
  {
    id: 5193,
    uid: '0d0fc423-9846-47a9-8dcb-4613a674b780',
    vin: 'S9XSOMM79O0084941',
    make_and_model: 'BMW X5',
    color: 'Violet',
    transmission: 'Automatic',
    drive_type: 'RWD',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Minivan',
    car_options: [
      'A/C: Rear',
      'Alarm',
      'A/C: Rear',
      'MP3 (Single Disc)',
      'Airbag: Side',
      'CD (Multi Disc)',
    ],
    specs: [
      'Optitron electroluminescent instrumentation',
      'Cargo-area tie down loops',
      'Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages',
      'Anti-lock 4-wheel performance disc brakes',
      'Vehicle dynamics integrated management (VDIM) system -inc: vehicle stability control (VSC), traction control (TRAC)',
      'Pwr front vented disc/rear drum brakes',
      'Vibration-dampening liquid-filled engine mounts',
      'Enhanced accident response system unlocks the doors, shuts off the fuel pump and turns on interior lights after airbag deploys',
    ],
    doors: 4,
    mileage: 37057,
    kilometrage: 24490,
    license_plate: 'PDF-9182',
  },
  {
    id: 6350,
    uid: '8f172043-4352-45f6-9feb-a8239910088c',
    vin: '9L7U2075930K07353',
    make_and_model: 'Honda Accord',
    color: 'Red',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Electric',
    car_type: 'SUV',
    car_options: [
      'Bucket Seats',
      'Keyless Entry',
      'MP3 (Multi Disc)',
      'AM/FM Stereo',
      'Keyless Entry',
      'Fog Lights',
    ],
    specs: [
      'Tire pressure monitoring system (TPMS)',
      'Energy absorbing steering column',
      'Rear body-color spoiler',
      'Energy absorbing steering column',
      'Tool kit',
      'Grain-matched wood trim -inc: center console, dash, door panels',
    ],
    doors: 1,
    mileage: 73830,
    kilometrage: 89839,
    license_plate: 'EUO-8657',
  },
  {
    id: 747,
    uid: '0c3b3ea1-ca6f-4a8d-84f9-0a4304948e7b',
    vin: '3U8AFH2H0P0I72955',
    make_and_model: 'Ford Focus',
    color: 'Green',
    transmission: 'Automatic',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Ethanol',
    car_type: 'Wagon',
    car_options: [
      'Moonroof/Sunroof',
      'DVD System',
      'Cassette Player',
      'Rear Window Defroster',
      'Keyless Entry',
    ],
    specs: [
      'Body color folding remote-controlled pwr mirrors',
      '200mm front axle',
      'Dual front knee airbags',
      'Dual bright exhaust tips',
      'Body color grille',
      'Dual front knee airbags',
      'Rain-sensing wipers',
      'Emergency interior trunk release',
    ],
    doors: 1,
    mileage: 62561,
    kilometrage: 52615,
    license_plate: 'JHL-4130',
  },
  {
    id: 4230,
    uid: '36e4d82c-9a56-4a4d-8cee-7d2848b86b26',
    vin: '149OPT1J63A801490',
    make_and_model: 'Toyota Prius',
    color: 'Grey',
    transmission: 'Automanual',
    drive_type: 'FWD',
    fuel_type: 'Gasoline',
    car_type: 'Coupe',
    car_options: [
      'Airbag: Side',
      'Premium Sound',
      'A/C: Front',
      'Memory Seats',
      'Alloy Wheels',
    ],
    specs: [
      'Integrated fog lamps',
      'Trailer tow wiring harness',
      'Dual-stage front airbags w/occupant classification system',
      'Traveler/mini trip computer',
      '"Flipper" liftgate glass',
      'Optitron electroluminescent instrumentation',
    ],
    doors: 1,
    mileage: 14475,
    kilometrage: 44135,
    license_plate: 'QLQ-1565',
  },
  {
    id: 715,
    uid: 'efc6ab91-3cc7-4aa3-8b65-dbc29135a9dd',
    vin: 'YUFER2HVSC0308631',
    make_and_model: 'Honda CR-V',
    color: 'White',
    transmission: 'Automatic',
    drive_type: 'RWD',
    fuel_type: 'Ethanol',
    car_type: 'Wagon',
    car_options: [
      'Power Seats',
      'Alloy Wheels',
      'Moonroof/Sunroof',
      'Power Seats',
      'Fog Lights',
      'A/C: Front',
      'Third Row Seats',
      'Third Row Seats',
    ],
    specs: [
      'Rear body-color spoiler',
      'Front/rear aluminum multi-link double joint suspension w/coil springs',
      'Vehicle info center',
      'Sentry Key theft deterrent system',
      'Silver finish interior door handles',
      'Fog lamps',
      'Grain-matched wood trim -inc: center console, dash, door panels',
      'Monotone paint',
      'Body color fascias w/bright insert',
    ],
    doors: 4,
    mileage: 70006,
    kilometrage: 73819,
    license_plate: 'YEP-8725',
  },
  {
    id: 7785,
    uid: '28a8016c-43bc-4fc1-9202-19fe815b2d58',
    vin: '4IO84AF2KBB890133',
    make_and_model: 'Lincoln Navigator',
    color: 'White',
    transmission: 'Automatic',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Compressed Natural Gas',
    car_type: 'Cargo Van',
    car_options: [
      'Alloy Wheels',
      'Rear Window Defroster',
      'Bucket Seats',
      'DVD System',
      'Tinted Glass',
      'CD (Single Disc)',
      'Keyless Entry',
    ],
    specs: [
      '4.6L DOHC 32-valve V8 engine -inc: DI & SFI dual fuel injection, dual variable valve timing w/intelligence & electronically controlled intake (VVT-iE), aluminum block & heads',
      'Body color fascias w/bright insert',
      'Energy absorbing steering column',
      'Front wheel drive',
      'Tilt steering column',
      'Body color door handles',
    ],
    doors: 1,
    mileage: 27817,
    kilometrage: 72966,
    license_plate: 'VQX-9665',
  },
  {
    id: 836,
    uid: '535228c5-f60a-4043-aff9-8726d88d745c',
    vin: '9CCY43T5UV0337409',
    make_and_model: 'Lincoln Navigator',
    color: 'Red',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'Compressed Natural Gas',
    car_type: 'Regular Cab Pickup',
    car_options: [
      'Integrated Phone',
      'Fog Lights',
      'A/C: Rear',
      'MP3 (Single Disc)',
      'Airbag: Driver',
      'Navigation',
      'AM/FM Stereo',
      'Power Seats',
    ],
    specs: [
      'Electric speed-sensitive variable-assist pwr steering',
      'Front/rear spot-lamp illumination',
      '"Flipper" liftgate glass',
      'Leather-wrapped shift knob',
      'Black windshield molding',
      'Supplemental side curtain air bags',
      'Floor carpeting',
      'Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages',
    ],
    doors: 1,
    mileage: 33201,
    kilometrage: 89160,
    license_plate: 'EWH-4010',
  },
  {
    id: 7233,
    uid: '1c2bfe55-04f0-46ee-87d5-2fc126ad8b0b',
    vin: 'GQ06XS8Q590B86943',
    make_and_model: 'Nissan Juke',
    color: 'Black',
    transmission: 'Automatic',
    drive_type: 'RWD',
    fuel_type: 'Gasoline',
    car_type: 'Hatchback',
    car_options: [
      'Premium Sound',
      'Power Locks',
      'Integrated Phone',
      'Airbag: Side',
      'Integrated Phone',
    ],
    specs: [
      'Front wheel drive',
      'Trailer tow wiring harness',
      'Brake assist',
      'Xenon high-intensity discharge (HID) headlamps -inc: adaptive front lighting system, delayed auto-off',
      '3-point rear center seat belts',
      'Direct-type tire pressure monitor system',
    ],
    doors: 3,
    mileage: 14849,
    kilometrage: 70438,
    license_plate: 'IZU-2294',
  },
  {
    id: 113,
    uid: 'd380fb0c-bb0a-42b4-881f-18474a9842f8',
    vin: 'A7IJ156NI8K008772',
    make_and_model: 'Honda CR-V',
    color: 'Orange',
    transmission: 'Automatic',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Ethanol',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Power Locks',
      'Power Steering',
      'AM/FM Stereo',
      'Power Seats',
      'Moonroof/Sunroof',
    ],
    specs: [
      'Pwr steering cooler',
      'Front & rear passenger folding assist grips',
      'Dual front illuminated visor vanity mirrors',
      'Tire pressure monitoring system (TPMS)',
      'All-position 3-point seat belts -inc: outboard pretensioners & force limiters, dual front pwr shoulder height adjusters, rear outboard emergency auto locking retractors, driver emergency locking retractor',
      'First aid kit',
      'Rear door child safety locks',
      'Tachometer',
    ],
    doors: 3,
    mileage: 43061,
    kilometrage: 66657,
    license_plate: 'WGG-1344',
  },
  {
    id: 8047,
    uid: '540a62e3-56db-4ad1-a538-991516cbc588',
    vin: '6HV0QL4MVES122737',
    make_and_model: 'Audi S5',
    color: 'White',
    transmission: 'CVT',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Gasoline',
    car_type: 'Cargo Van',
    car_options: [
      'A/C: Front',
      'Power Steering',
      'Integrated Phone',
      'Airbag: Driver',
      'CD (Multi Disc)',
      'Rear Window Wiper',
      'Tow Package',
      'Memory Seats',
      'Premium Sound',
    ],
    specs: [
      'Brake assist',
      'Fog lamps',
      'Fasten seat belt warning light/chime',
      'Trim-panel-mounted storage net',
      'Run flat tires',
      'Enhanced accident response system unlocks the doors, shuts off the fuel pump and turns on interior lights after airbag deploys',
    ],
    doors: 3,
    mileage: 70044,
    kilometrage: 17917,
    license_plate: 'MGL-5671',
  },
  {
    id: 5089,
    uid: '278129d7-1d44-43f6-9ca5-dee766f746ae',
    vin: '90XJTM920BMG77134',
    make_and_model: 'Dodge Ram',
    color: 'Black',
    transmission: 'Automanual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Electric',
    car_type: 'Wagon',
    car_options: [
      'Power Windows',
      'Airbag: Side',
      'Rear Window Defroster',
      'MP3 (Single Disc)',
      'Fog Lights',
      'CD (Multi Disc)',
    ],
    specs: [
      'All-position 3-point seat belts -inc: outboard pretensioners & force limiters, dual front pwr shoulder height adjusters, rear outboard emergency auto locking retractors, driver emergency locking retractor',
      'Electronic control braking (ECB)',
      'Cargo area lamp',
      '1-piece chrome window surround',
      'Instrument cluster w/tachometer',
      'Battery saver',
    ],
    doors: 2,
    mileage: 86841,
    kilometrage: 76781,
    license_plate: 'EBN-1454',
  },
  {
    id: 211,
    uid: '9ec5e9f0-8ca9-4340-bb3f-e93ae127bb05',
    vin: '58W6YXSDDTR844883',
    make_and_model: 'Nissan Cube',
    color: 'Red',
    transmission: 'Manual',
    drive_type: 'AWD',
    fuel_type: 'Gasoline',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Airbag: Side',
      'Antilock Brakes',
      'Airbag: Side',
      'Cruise Control',
      'Navigation',
      'CD (Multi Disc)',
      'Cassette Player',
      'Power Seats',
    ],
    specs: [
      'Carpeted floor & cargo area',
      'Brake assist',
      'Immobilizer system',
      '200mm front axle',
      'Cargo compartment cover',
      '4-wheel ventilated pwr disc brakes -inc: brake override system',
    ],
    doors: 3,
    mileage: 80308,
    kilometrage: 38678,
    license_plate: 'EIN-4799',
  },
  {
    id: 4547,
    uid: '80993b14-9d1d-4b93-befb-b6246c8003ef',
    vin: 'K8DDC2NJ3N0387484',
    make_and_model: 'Honda CR-V',
    color: 'Violet',
    transmission: 'Manual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Electric',
    car_type: 'Wagon',
    car_options: [
      'Tinted Glass',
      'Third Row Seats',
      'Power Locks',
      'Fog Lights',
      'Tinted Glass',
      'Tinted Glass',
    ],
    specs: [
      'Leather-wrapped parking brake handle',
      'Tire pressure monitoring display',
      'Highline door trim panel',
      'Vehicle info center',
      'Tachometer',
      'Rear-window defogger w/auto-off timer',
    ],
    doors: 2,
    mileage: 89642,
    kilometrage: 82008,
    license_plate: 'NTW-4558',
  },
  {
    id: 4673,
    uid: '8ca6de78-4e09-454e-8e88-73dc1bea3945',
    vin: 'SW03JYUGPN0H40726',
    make_and_model: 'Chevy Camero',
    color: 'Beige',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'Compressed Natural Gas',
    car_type: 'SUV',
    car_options: [
      'A/C: Front',
      'MP3 (Single Disc)',
      'Alarm',
      'Airbag: Driver',
      'Alarm',
      'Antilock Brakes',
      'DVD System',
      'MP3 (Multi Disc)',
      'DVD System',
    ],
    specs: [
      'Traveler/mini trip computer',
      '4-wheel/4-channel anti-lock brake system (ABS)',
      'Luxury front & rear floor mats w/logo',
      'Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages',
      'Instrument cluster w/tachometer',
      'Dual front & rear cup holders',
      'Back-up camera',
    ],
    doors: 3,
    mileage: 25302,
    kilometrage: 16123,
    license_plate: 'YRK-1796',
  },
  {
    id: 7678,
    uid: '75064402-bd1e-4967-ad90-c85bed00856e',
    vin: 'LKUH2J58U2D811338',
    make_and_model: 'Ford F150',
    color: 'Orange',
    transmission: 'Automanual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'Airbag: Driver',
      'Cassette Player',
      'Fog Lights',
      'Keyless Entry',
      'Cassette Player',
      'AM/FM Stereo',
      'CD (Single Disc)',
      'Power Steering',
    ],
    specs: [
      'Rear door child safety locks',
      'Front side-impact airbags',
      'Front & rear side curtain airbags',
      'Rear window defroster',
      'Pwr front windows w/(1) touch up/down feature',
      'Silver accent IP trim finisher -inc: silver shifter finisher',
    ],
    doors: 2,
    mileage: 83970,
    kilometrage: 72917,
    license_plate: 'VQH-5407',
  },
  {
    id: 9804,
    uid: '05680eec-bbaa-401e-a226-d69b7280baef',
    vin: 'R0RNJ360V3X271551',
    make_and_model: 'Nissan Rogue',
    color: 'Yellow',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Cruise Control',
      'CD (Multi Disc)',
      'Cruise Control',
      'Airbag: Driver',
      'Tinted Glass',
      'Memory Seats',
    ],
    specs: [
      'Rear body-color spoiler',
      'Electrochromic pwr folding heated mirrors w/memory -inc: puddle lamps, integrated turn signals, auto reverse tilt-down',
      'Acoustic control induction system (ACIS)',
      'P235/50R18 all-season tires',
      'Trim-panel-mounted storage net',
      'Overhead console',
      'Dual-stage front airbags w/occupant classification system',
    ],
    doors: 2,
    mileage: 17079,
    kilometrage: 87496,
    license_plate: 'LSX-8117',
  },
  {
    id: 7895,
    uid: 'aa4b927b-d287-430c-bbf7-379070e83d5d',
    vin: '7W1845PX720N30691',
    make_and_model: 'Ford Fiesta',
    color: 'Green',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'Diesel',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'MP3 (Single Disc)',
      'DVD System',
      'Airbag: Driver',
      'Keyless Entry',
      'Power Steering',
      'Alarm',
      'Cruise Control',
      'Premium Sound',
    ],
    specs: [
      'XM satellite radio receiver -inc: 90 day trial subscription',
      'Water-repellent windshield & front door glass',
      'Quadra-Trac active on demand 4WD system',
      'Glove box lamp',
      '625-amp maintenance-free battery',
    ],
    doors: 4,
    mileage: 17689,
    kilometrage: 84422,
    license_plate: 'RTN-8015',
  },
  {
    id: 6874,
    uid: 'd8a24e3d-a86f-4c77-8b64-648d160774ed',
    vin: 'P4T1D598D7YU01029',
    make_and_model: 'BMW 328i',
    color: 'Grey',
    transmission: 'Automatic',
    drive_type: 'RWD',
    fuel_type: 'Ethanol',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'AM/FM Stereo',
      'Airbag: Driver',
      'Moonroof/Sunroof',
      'Third Row Seats',
      'Third Row Seats',
      'Rear Window Defroster',
      'Power Windows',
    ],
    specs: [
      '4.6L DOHC 32-valve V8 engine -inc: DI & SFI dual fuel injection, dual variable valve timing w/intelligence & electronically controlled intake (VVT-iE), aluminum block & heads',
      'Rear window defroster w/timer',
      'Rear bench seat -inc: (3) adjustable headrests',
      'Rear window defroster w/timer',
      'Vibration-dampening liquid-filled engine mounts',
      'Driver & front passenger advanced multistage airbags w/occupant sensors',
      'Dual illuminated visor vanity mirrors',
    ],
    doors: 2,
    mileage: 54564,
    kilometrage: 65948,
    license_plate: 'FXC-4054',
  },
  {
    id: 686,
    uid: '16e39689-3d0f-4aa5-85e6-f52c19647173',
    vin: '7JHQ9ISBI2DS48368',
    make_and_model: 'Chevy Camero',
    color: 'Blue',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Gasoline',
    car_type: 'Hatchback',
    car_options: [
      'Third Row Seats',
      'MP3 (Multi Disc)',
      'Rear Window Wiper',
      'AM/FM Stereo',
      'Tinted Glass',
      'Rear Window Defroster',
      'A/C: Front',
      'Airbag: Driver',
      'Rear Window Wiper',
    ],
    specs: [
      'Black windshield molding',
      'Multi-reflector halogen headlamps',
      'P235/50R18 all-season tires',
      '4-wheel/4-channel anti-lock brake system (ABS)',
      'Chrome bodyside molding',
      'Electric speed-sensitive variable-assist pwr steering',
    ],
    doors: 2,
    mileage: 59127,
    kilometrage: 87738,
    license_plate: 'SNY-9753',
  },
  {
    id: 6364,
    uid: '76aec296-4e26-4206-ac1c-a920045f1c4b',
    vin: 'ZA07OD0T35V427730',
    make_and_model: 'BMW X5',
    color: 'Black',
    transmission: 'Manual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Gasoline',
    car_type: 'Wagon',
    car_options: [
      'MP3 (Multi Disc)',
      'MP3 (Multi Disc)',
      'Tinted Glass',
      'Third Row Seats',
      'Rear Window Defroster',
      'MP3 (Multi Disc)',
      'A/C: Rear',
      'Integrated Phone',
    ],
    specs: [
      'Front/rear crumple zones',
      'Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats',
      'Leather-wrapped shift knob',
      'Immobilizer system',
      'Leather-wrapped parking brake handle',
      '4-wheel/4-channel anti-lock brake system (ABS)',
      'Cargo compartment lamp',
      '3.73 axle ratio',
    ],
    doors: 2,
    mileage: 47642,
    kilometrage: 80168,
    license_plate: 'ALZ-3498',
  },
  {
    id: 294,
    uid: '1bd0af5b-f644-402d-af4a-736274af2bd5',
    vin: '1I5DIFD87I0V33544',
    make_and_model: 'Ford F150',
    color: 'Green',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'Ethanol',
    car_type: 'Cargo Van',
    car_options: [
      'Alarm',
      'Airbag: Side',
      'CD (Multi Disc)',
      'MP3 (Single Disc)',
      'Airbag: Driver',
      'DVD System',
      'Tinted Glass',
    ],
    specs: [
      'Dual front & rear cup holders',
      'Collapsible steering column',
      '200mm front axle',
      'Multi-info display -inc: driving range, average MPG, current MPG, average speed, outside temp, elapsed time, maintenance & diagnostic messages',
      'Body color door handles',
      'Laminated side window glass',
      'Pwr front windows w/(1) touch up/down feature',
      'Dana 44/226mm rear axle',
    ],
    doors: 1,
    mileage: 53386,
    kilometrage: 15957,
    license_plate: 'MNE-7321',
  },
  {
    id: 1546,
    uid: '5594329c-c3a2-4971-b4a1-3c82a9df1dc7',
    vin: 'SF6OIAN168UO45082',
    make_and_model: 'Toyota Prius',
    color: 'Violet',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'Electric',
    car_type: 'Wagon',
    car_options: [
      'CD (Single Disc)',
      'Rear Window Wiper',
      'Fog Lights',
      'Airbag: Driver',
      'Airbag: Passenger',
      'Rear Window Wiper',
      'DVD System',
      'Fog Lights',
      'Airbag: Passenger',
    ],
    specs: [
      'Emergency interior trunk release',
      'Quadra-Trac active on demand 4WD system',
      'Body color sill extension',
      'XM satellite radio receiver -inc: 90 day trial subscription',
      'Body color fascias w/bright insert',
      'Tire pressure monitoring system (TPMS)',
      'Traveler/mini trip computer',
      'Electronic brakeforce distribution (EBD) w/brake assist (BA) -inc: Smart stop technology',
    ],
    doors: 3,
    mileage: 86931,
    kilometrage: 74126,
    license_plate: 'EFG-8349',
  },
  {
    id: 8299,
    uid: 'c9283a90-53f9-42b6-aaa7-afba1e92f2c5',
    vin: 'J25SDN6B5CZD28713',
    make_and_model: 'Nissan Cube',
    color: 'Orange',
    transmission: 'CVT',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Wagon',
    car_options: [
      'Alloy Wheels',
      'MP3 (Single Disc)',
      'Antilock Brakes',
      'Alloy Wheels',
      'Power Locks',
      'A/C: Front',
      'Tow Package',
      'Premium Sound',
    ],
    specs: [
      'Rear window defroster',
      'Driver & front passenger map pockets',
      'Pwr rear liftgate release',
      '1-piece chrome window surround',
      'Monotone paint',
      'Rear window defroster',
      'Cargo compartment lamp',
      'Side-impact door beams',
      'Multi-reflector halogen headlamps',
    ],
    doors: 3,
    mileage: 68509,
    kilometrage: 44644,
    license_plate: 'SIN-7462',
  },
  {
    id: 5236,
    uid: '6a59399f-f969-405a-841a-449af3d94e61',
    vin: 'WB5802C5730F18140',
    make_and_model: 'Nissan Rogue',
    color: 'Blue',
    transmission: 'Manual',
    drive_type: 'AWD',
    fuel_type: 'Compressed Natural Gas',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Leather Interior',
      'AM/FM Stereo',
      'Third Row Seats',
      'Bucket Seats',
      'Third Row Seats',
      'Moonroof/Sunroof',
    ],
    specs: [
      'Driver & front passenger map pockets',
      'Dana 44/226mm rear axle',
      'Impact-dissipating upper interior trim',
      'Silver accent IP trim finisher -inc: silver shifter finisher',
      'Electronic control braking (ECB)',
      '6.1L SRT V8 "Hemi" engine',
    ],
    doors: 2,
    mileage: 32117,
    kilometrage: 88138,
    license_plate: 'IVY-6093',
  },
  {
    id: 9502,
    uid: '056ea896-c030-430b-aa7b-9cd2fc43ece8',
    vin: 'SDIT81I025KX90736',
    make_and_model: 'Audi A4',
    color: 'Black',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'Airbag: Side',
      'Navigation',
      'Rear Window Wiper',
      'AM/FM Stereo',
      'Alarm',
      'Airbag: Driver',
      'Airbag: Side',
      'Power Windows',
    ],
    specs: [
      'Variable intermittent windshield wipers w/mist function',
      'Optitron electroluminescent instrumentation',
      'Body color front/rear bumpers',
      'Front/rear crumple zones',
      'Front/rear aluminum multi-link double joint suspension w/coil springs',
      'Electronic control braking (ECB)',
      'Cargo-area tie down loops',
      'Variable intermittent windshield wipers w/mist function',
    ],
    doors: 1,
    mileage: 31297,
    kilometrage: 10439,
    license_plate: 'QEM-7904',
  },
  {
    id: 4017,
    uid: '0d814db4-4c0b-43aa-855a-2102751ebd4d',
    vin: 'XKRY1OKR780819988',
    make_and_model: 'Toyota Camry',
    color: 'Beige',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Diesel',
    car_type: 'Coupe',
    car_options: [
      'AM/FM Stereo',
      'Leather Interior',
      'Airbag: Side',
      'Power Locks',
      'DVD System',
      'Airbag: Driver',
      'Power Windows',
      'MP3 (Single Disc)',
    ],
    specs: [
      'Passenger assist handles',
      'Tire pressure monitoring display',
      '3-point ELR/ALR rear seat belts at all positions',
      'Child safety rear door locks',
      'Rear body-color spoiler',
      'Full-length floor console',
      'Cargo compartment cover',
      'Collapsible steering column',
      'Pwr front vented disc/rear drum brakes',
    ],
    doors: 2,
    mileage: 71236,
    kilometrage: 20210,
    license_plate: 'XUN-1268',
  },
  {
    id: 5899,
    uid: '4d206a3b-ca6d-482b-9004-12dd157fa629',
    vin: 'TW528Y2L780T32246',
    make_and_model: 'BMW M5',
    color: 'White',
    transmission: 'Automanual',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Electric',
    car_type: 'SUV',
    car_options: [
      'CD (Multi Disc)',
      'Moonroof/Sunroof',
      'Antilock Brakes',
      'Airbag: Side',
      'AM/FM Stereo',
      'Keyless Entry',
      'Keyless Entry',
      'Power Locks',
    ],
    specs: [
      'Body color sill extension',
      '1-piece chrome window surround',
      'Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats',
      'Cargo area lamp',
      'Electronic control braking (ECB)',
      'Reversible/waterproof cargo storage',
      'Silver accent IP trim finisher -inc: silver shifter finisher',
    ],
    doors: 3,
    mileage: 60034,
    kilometrage: 63759,
    license_plate: 'UGC-9532',
  },
  {
    id: 6047,
    uid: 'ea4591ca-e3bb-4bcc-8b50-f18d15bc370b',
    vin: 'K792834O2TEX81094',
    make_and_model: 'Audi A4',
    color: 'Red',
    transmission: 'Automatic',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Gasoline Hybrid',
    car_type: 'Crew Cab Pickup',
    car_options: [
      'Memory Seats',
      'Airbag: Side',
      'A/C: Rear',
      'Alarm',
      'CD (Multi Disc)',
      'Alloy Wheels',
    ],
    specs: [
      'Fog lamps',
      'Dual chrome exhaust tips',
      'Universal garage door opener',
      'Black windshield molding',
      'Fixed long mast antenna',
      'Tire pressure monitoring system (TPMS)',
      'Driver & front passenger advanced multistage airbags w/occupant sensors',
    ],
    doors: 3,
    mileage: 29990,
    kilometrage: 25556,
    license_plate: 'RYH-1492',
  },
  {
    id: 8380,
    uid: 'd8e56f7f-2925-4b87-a80c-70c3d29cb3cf',
    vin: '2L4O2K396HJ634063',
    make_and_model: 'Chevy Silverado',
    color: 'Violet',
    transmission: 'CVT',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Hatchback',
    car_options: [
      'Premium Sound',
      'Bucket Seats',
      'CD (Multi Disc)',
      'Power Steering',
      'A/C: Front',
      'CD (Single Disc)',
      'Alarm',
    ],
    specs: [
      'Variable intermittent windshield wipers w/mist function',
      'Run flat tires',
      '"Flipper" liftgate glass',
      'Dual-zone automatic climate control system -inc: smog sensor, auto recirculation, clear air filter, pollen filter',
      '160-amp alternator',
      'Child restraint seat anchors for outboard positions',
      'Sentry Key theft deterrent system',
      'Child safety rear door locks',
    ],
    doors: 1,
    mileage: 76341,
    kilometrage: 63892,
    license_plate: 'TWE-1577',
  },
  {
    id: 1111,
    uid: '38aedafc-22e6-4c50-ba75-567a5128f650',
    vin: 'Y4YEFZ6580BH27092',
    make_and_model: 'Dodge Ram',
    color: 'Grey',
    transmission: 'Automatic',
    drive_type: 'AWD',
    fuel_type: 'E-85/Gasoline',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Navigation',
      'Bucket Seats',
      'CD (Multi Disc)',
      'Tinted Glass',
      'Antilock Brakes',
      'Fog Lights',
      'Power Locks',
      'Keyless Entry',
      'Power Locks',
    ],
    specs: [
      'Brake assist',
      'Torsion beam rear suspension w/stabilizer bar',
      'Carpeted floor & cargo area',
      'Fixed long mast antenna',
      'Body color folding remote-controlled pwr mirrors',
      'Full-length floor console',
      '60/40 folding rear seat',
      'Illuminated entry',
    ],
    doors: 2,
    mileage: 79585,
    kilometrage: 78438,
    license_plate: 'EFC-3469',
  },
  {
    id: 555,
    uid: '783f70b3-715a-4fd3-86bd-ab7f78f4e1dd',
    vin: '15SDP2204N0116679',
    make_and_model: 'Dodge Ram',
    color: 'Red',
    transmission: 'CVT',
    drive_type: 'RWD',
    fuel_type: 'Electric',
    car_type: 'Coupe',
    car_options: [
      'Power Seats',
      'Airbag: Side',
      'MP3 (Single Disc)',
      'Memory Seats',
      'Antilock Brakes',
    ],
    specs: [
      'Electric pwr rack & pinion steering (EPS)',
      'Child safety rear door locks',
      'Pwr accessory delay',
      'Pwr 8-way driver seat w/4-way front passenger seat',
      'LED lights -inc: brake lamps, tail lamps, license plate',
      'Integrated fog lamps',
      'Carpeted floor & cargo area',
      'Tip start system',
    ],
    doors: 1,
    mileage: 18012,
    kilometrage: 17475,
    license_plate: 'VOH-2060',
  },
  {
    id: 6189,
    uid: '9aef25a6-036b-48a1-a855-6f81d406eb12',
    vin: 'M135AP8YC40J24490',
    make_and_model: 'Dodge Durango',
    color: 'Red',
    transmission: 'CVT',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Electric',
    car_type: 'Extended Cab Pickup',
    car_options: [
      'Alloy Wheels',
      'Power Locks',
      'Power Seats',
      'Tow Package',
      'Bucket Seats',
      'A/C: Front',
    ],
    specs: [
      'Front wheel drive',
      'Illuminated entry',
      '200mm front axle',
      'Torsion beam rear suspension w/stabilizer bar',
      'Tip start system',
      'Body color front/rear bumpers',
      'Tip start system',
      'Black windshield molding',
      'Sentry Key theft deterrent system',
    ],
    doors: 1,
    mileage: 83427,
    kilometrage: 24892,
    license_plate: 'HQE-1981',
  },
  {
    id: 9230,
    uid: '23f6d7a1-9519-4747-9660-3320a4319638',
    vin: 'MG738484I4OX12654',
    make_and_model: 'Toyota Corolla',
    color: 'Green',
    transmission: 'Automanual',
    drive_type: 'AWD',
    fuel_type: 'Gasoline Hybrid',
    car_type: 'Passenger Van',
    car_options: [
      'Tinted Glass',
      'Integrated Phone',
      'A/C: Front',
      'Keyless Entry',
      'Bucket Seats',
      'CD (Multi Disc)',
    ],
    specs: [
      'Tire pressure monitoring system (TPMS)',
      'Front side-impact airbags',
      'Dual note horn',
      'Supplemental side curtain air bags',
      'Electric speed-sensitive variable-assist pwr steering',
      'Dual front & rear cup holders',
    ],
    doors: 3,
    mileage: 68192,
    kilometrage: 61588,
    license_plate: 'DIM-6429',
  },
  {
    id: 6080,
    uid: 'be50bea9-e88d-426e-bfcc-c5b5fef2d40f',
    vin: 'KUFVPA10GDVL67071',
    make_and_model: 'BMW 328i',
    color: 'Yellow',
    transmission: 'Automanual',
    drive_type: 'FWD',
    fuel_type: 'Diesel',
    car_type: 'Cargo Van',
    car_options: [
      'Cruise Control',
      'Leather Interior',
      'Rear Window Wiper',
      'Premium Sound',
      'Power Steering',
      'A/C: Front',
      'Airbag: Side',
      'Power Windows',
      'MP3 (Multi Disc)',
    ],
    specs: [
      'Security alarm',
      'Roof mounted antenna',
      'Tire pressure monitoring system (TPMS)',
      '625-amp maintenance-free battery',
      'Fog lamps',
      'Enhanced accident response system unlocks the doors, shuts off the fuel pump and turns on interior lights after airbag deploys',
    ],
    doors: 4,
    mileage: 58788,
    kilometrage: 61305,
    license_plate: 'YSM-3026',
  },
  {
    id: 5469,
    uid: 'd3f4975b-10d5-4a5f-b42d-9c709f8953f8',
    vin: '42BB78Z95F0I80961',
    make_and_model: 'Audi A4',
    color: 'Blue',
    transmission: 'CVT',
    drive_type: '4x2/2-wheel drive',
    fuel_type: 'Ethanol',
    car_type: 'Wagon',
    car_options: [
      'Tinted Glass',
      'A/C: Rear',
      'Moonroof/Sunroof',
      'Alarm',
      'AM/FM Stereo',
    ],
    specs: [
      'Center console',
      'Overhead console',
      'Driver & front passenger advanced multistage airbags w/occupant sensors',
      'Body color fascias w/bright insert',
      '1-piece chrome window surround',
      'Enhanced accident response system unlocks the doors, shuts off the fuel pump and turns on interior lights after airbag deploys',
      'Dual bright exhaust tips',
    ],
    doors: 1,
    mileage: 42924,
    kilometrage: 81767,
    license_plate: 'FQJ-1488',
  },
  {
    id: 694,
    uid: 'd45037ac-1b5b-4067-929f-03224dc434f9',
    vin: '1NE45060C60G52032',
    make_and_model: 'Honda CR-V',
    color: 'Orange',
    transmission: 'Automanual',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Electric',
    car_type: 'Coupe',
    car_options: [
      'Cruise Control',
      'DVD System',
      'Leather Interior',
      'A/C: Rear',
      'Premium Sound',
    ],
    specs: [
      'Collapsible steering column',
      'Front/rear stabilizer bars',
      'Pwr 8-way driver seat w/4-way front passenger seat',
      'Torsion beam rear suspension w/stabilizer bar',
      'Leather-wrapped steering wheel w/audio controls',
      'Fog lamps',
      'Variable intermittent windshield wipers w/mist function',
      'Pwr front windows w/(1) touch up/down feature',
    ],
    doors: 1,
    mileage: 71710,
    kilometrage: 30079,
    license_plate: 'FKU-8317',
  },
  {
    id: 5634,
    uid: 'a05d6050-21ce-49d0-b619-18d494a2787c',
    vin: '32D30ESXGS0F52006',
    make_and_model: 'Ford Focus',
    color: 'Beige',
    transmission: 'Manual',
    drive_type: 'RWD',
    fuel_type: 'Diesel',
    car_type: 'Coupe',
    car_options: [
      'Power Steering',
      'Power Windows',
      'Premium Sound',
      'Integrated Phone',
      'Integrated Phone',
      'Power Steering',
    ],
    specs: [
      '1-piece chrome window surround',
      'Electrochromic rearview mirror',
      'Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats',
      'Electronic throttle control system w/intelligence (ETCS-i)',
      'Body color front/rear bumpers',
      'Reclining front bucket seats -inc: active head restraints, double-thickness foam in front seats',
    ],
    doors: 3,
    mileage: 24776,
    kilometrage: 39779,
    license_plate: 'RLP-4238',
  },
  {
    id: 7031,
    uid: '17c48271-d4df-42a1-8142-b3f0b17a9579',
    vin: '2R95WM5SN5OE19428',
    make_and_model: 'Honda Accord',
    color: 'Black',
    transmission: 'Automatic',
    drive_type: '4x4/4-wheel drive',
    fuel_type: 'Gasoline',
    car_type: 'SUV',
    car_options: [
      'Third Row Seats',
      'Rear Window Wiper',
      'Airbag: Passenger',
      'Power Seats',
      'MP3 (Single Disc)',
      'DVD System',
      'Tow Package',
    ],
    specs: [
      'Impact-dissipating upper interior trim',
      'Tip start system',
      '(2) aux 12V pwr outlets -inc: (1) in center console, (1) w/cigarette lighter',
      'Security alarm',
      'First aid kit',
    ],
    doors: 1,
    mileage: 41732,
    kilometrage: 25720,
    license_plate: 'YVM-7436',
  },
];
